[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "/api/*"
  to = "http://54.199.68.197:8081/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"