export const HOST = 'https://be-junittest-dbclpm.onrender.com/api/v1'
export const SUPPLIER_API = HOST + '/suppliers'
export const ORDER_API = HOST + '/orders'
export const PRODUCT_API = HOST + '/products'
export const CATEGORY_API = HOST + '/category'
export const EMPLOYEE_API = HOST + '/employees/list'